---
- name: Stop & mask timesyncd
  ansible.builtin.systemd:
    name: systemd-timesyncd
    state: stopped
    enabled: no
    masked: yes
  when: ansible_service_mgr == 'systemd'

- name: Remove timesyncd
  ansible.builtin.apt:
    name: systemd-timesyncd
    state: absent
    purge: yes
    update_cache: yes
